[package]
name = "flora"
version = "0.1.0"
authors = ["Tim Seckinger <seckinger.tim@gmail.com>"]
edition = "2018"

[dependencies]

[workspace]
members = [
  "dot_gen",
  "model",
  "parser",
  "syntax",
  "syntax_to_model",
]
