[package]
name = "flora_syntax_to_model"
version = "0.1.0"
authors = ["Tim Seckinger <seckinger.tim@gmail.com>"]
edition = "2018"

[dependencies]
flora_syntax = { path = "../syntax" }
flora_model = { path = "../model" }
